### ISSUE TITLE
Fix to retrieve libva version

### ISSUE THREAD

**Issue by SiewHoon** [01org/libva-utils#56] opened 2017-08-15 02:30 UTC
vainfo fail to retrieve the libva version number after the libva-utils split from libva.
This is patch use to retrieve the libva version. 
It require the fix changed (https://github.com/01org/libva/issues/95) in libva as well.

**Comment by xhaihao** [comment] 2017-08-16 04:01
A duplicate of https://github.com/01org/libva-utils/issues/41

**Closed by xhaihao** 2017-08-16 04:01 UTC
Labels: bug, duplicate
